### ISSUE TITLE
[EMBED] Upgrade UI and add support for playlists

### ISSUE THREAD

**Issue by blastshielddown** [wavlake/embed#17]
- [x] Upgrade UI according to the attached mock-up
- [x] Add new zap UI
- [x] Add support for custom playlists (depends on https://github.com/wavlake/catalog/issues/293)

General:
UI for the embed player should be upgraded to match the attached mock-up as closely as possible for both single mode and multi-track mode. In other words, in any context where there is more than one track (album/artist/podcast/playlist) the multi-track version of the player should be enabled. Any single track or episode should be presented with the full album art view. Note that the embed player uses both catalog (for content data) and server (for invoice handling). Plan is to stick to this pattern for this upgrade.

Zap UI:
We would like to create a new UI for when a user presses the zap button: the playlist should appear to "flip over" like a card to reveal the form where a user can enter the sat amount and message to zap. The animation here is a nice to have. A simple modal would also work here. We can use the same background and layout as we do for zaps on .com (white background included).

Playlist feature:
Only dependency to completing this task is creating new, custom playlist functionality in catalog. The goal is to make one custom playlist we manage shareable to start. The playlist itself does not have to be boostable in this iteration. Just the individual content. We will add boostable playlists later.

![Image](https://github.com/wavlake/embed/assets/77257032/699e2184-718f-4f02-9c7f-479b68bdcb6a)

<img width="437" alt="Screenshot 2024-02-08 at 1 23 03 PM" src="https://github.com/wavlake/embed/assets/77257032/57e8e58f-f3d0-4020-8fef-0cd236eeaff4">

**Comment by joshr4** [comment]
for the link preview image, looks like a collage of 4 cover arts, can try to use something like https://github.com/lukechilds/merge-images to create this dynamically

**Comment by blastshielddown** [comment]
looks promising. i think we should make the link preview image a separate task for now, can be a nice to have after the main functionality is in place

**Comment by blastshielddown** [comment]
#18
